name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # ensure dev tools present even if not in requirements.txt
          pip install flake8 pytest

      - name: Lint with flake8
        run: |
          # lint *only* your code; adjust paths if needed
          flake8 ml/ main.py train_model.py local_api.py tests/ \
            --ignore=E302,E501 \
            --exclude=__pycache__,.git,.venv,venv,fastapi,**/site-packages/**

      - name: Run tests
        run: |
          pytest -v